apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "aaa-bcde"
  description: backstage docs-test
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_aaa/test-spring-boot
    github.com/project-slug: 'hmcts-test/test-spring-boot'
  tags:
    - java
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: service
  system: aaa
  lifecycle: experimental
  owner: dts_platform_operations
